[2023-11-26 09:41:33,753] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:41:33] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:42:49,538] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:42:49] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:46:17,721] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:46:17] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:47:03,433] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:47:03] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:48:53,123] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:48:53] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:50:01,022] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:50:01] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:52:24,793] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:52:24] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:52:57,014] WARNING predict() L113  Erro ao adicionar cliente, Cliente já existente na base :/ - call_trace=C:\Users\Catarina Sabbadim\Desktop\api\app.py L113 
[2023-11-26 09:52:57,017] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:52:57] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:53:55,531] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:53:55] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:56:31,277] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:56:31] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:56:56,087] WARNING predict() L113  Erro ao adicionar cliente, Cliente já existente na base :/ - call_trace=C:\Users\Catarina Sabbadim\Desktop\api\app.py L113 
[2023-11-26 09:56:56,089] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:56:56] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:57:41,557] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:57:41] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 09:59:42,461] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 09:59:42] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 10:00:08,241] WARNING predict() L113  Erro ao adicionar cliente, Cliente já existente na base :/ - call_trace=C:\Users\Catarina Sabbadim\Desktop\api\app.py L113 
[2023-11-26 10:00:08,244] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 10:00:08] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 10:01:39,381] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 10:01:39] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 10:02:07,738] WARNING predict() L113  Erro ao adicionar cliente, Cliente já existente na base :/ - call_trace=C:\Users\Catarina Sabbadim\Desktop\api\app.py L113 
[2023-11-26 10:02:07,739] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 10:02:07] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 10:03:31,839] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 10:03:31] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 10:04:12,913] WARNING predict() L113  Erro ao adicionar cliente, Cliente já existente na base :/ - call_trace=C:\Users\Catarina Sabbadim\Desktop\api\app.py L113 
[2023-11-26 10:04:12,914] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 10:04:12] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:36,120] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.10.167:5000 (Press CTRL+C to quit) - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:36,533] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:36] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:36,606] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:36] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:36,608] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:36] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:36,738] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:36] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:37,048] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:37] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:37,052] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:37] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:42,798] WARNING predict() L113  Erro ao adicionar cliente, Cliente já existente na base :/ - call_trace=C:\Users\Catarina Sabbadim\Downloads\mv\api\app.py L113 
[2023-11-26 13:06:42,801] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:42] "[31m[1mPOST /cliente HTTP/1.1[0m" 409 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:49,735] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:49] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:06:58,648] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:06:58] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:07:40,633] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:07:40] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:08:05,658] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:08:05] "GET /clientes HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:09:26,963] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:09:26] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:09:47,278] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:09:47] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:10:09,180] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:10:09] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:10:19,368] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:10:19] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:10:31,803] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:10:31] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:10:54,932] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:10:54] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
[2023-11-26 13:11:06,189] INFO _log() L224  127.0.0.1 - - [26/Nov/2023 13:11:06] "POST /cliente HTTP/1.1" 200 - - call_trace=C:\Users\Catarina Sabbadim\AppData\Roaming\Python\Python37\site-packages\werkzeug\_internal.py L224 
